### PR TITLE
FIX #29: use Tini (offiically supported by Docker) to reap defunct glusterfs processes.

### LINKED ISSUE #29: docker stop command create <defunct> process
Every time a container having a glusterfs docker volume mounted is stopped, a daemon process typed as \<defunct\> is created.

> docker run --rm -it -v my-glusterfs-volume:/work alpine

After a control-c, ps aux shows defunct. This is what ps command shows after 6 starts and stops.

> root     24438  0.0  0.0      0     0 ?        Zs   11:04   0:00 [glusterfs] \<defunct\>
> root     24560  0.0  0.0      0     0 ?        Zs   11:04   0:00 [glusterfs] \<defunct\>
> root     24801  0.0  0.0      0     0 ?        Zs   11:05   0:00 [glusterfs] \<defunct\>
> root     25263  0.0  0.0      0     0 ?        Zs   11:07   0:00 [glusterfs] \<defunct\>
> root     25381  0.0  0.0      0     0 ?        Zs   11:08   0:00 [glusterfs] \<defunct\>
> root     25529  0.0  0.0      0     0 ?        Zs   11:08   0:00 [glusterfs] \<defunct\>

Regards,

### PR DESCRIPTION
**Pull request by ximon18**
Fixes #29.

### CODE REVIEW

**Comment by btheu** [comment]
Tested it, works with familiar situation.

**Comment by ximon18** [comment]
If there’s no activity here soon I can also fork the project and publish the fixed plugin on Docker hub myself if needed.

**Comment by trajano** [comment]
@ximon18 Please fork.  I haven't been able to make activity on this.

**Comment by ximon18** [comment]
Thanks @trajano, I'll do that.

**Comment by marcelo-ochoa** [comment]
I built from sources and applied above patch and solve problem of defunct process.
Thanks a lot @ximon18 !!

**Review by marcelo-ochoa — APPROVED** [review]
Confirmed, tini solved defunct process

**Comment by ximon18** [comment]
> @ximon18 Please fork. I haven't been able to make activity on this.

I still intend to do this, but with Covid-19 and other stuff I didn't get to it yet, and it's not as simple as just forking as I'd either want to split out the Gluster part from the other drivers (as I know nothing about them) or take them all on but then know how to build and test them, and as evidenced by the lack of activity on my part I wouldn't have been able to offer much until now in the way of active support for the project (I still depend on it and am happy to, the GlusterFS part at least, take it over).

**Comment by marcelo-ochoa** [comment]
@ximon18 I am preparing a new patch which includes this one and another module to mount S3Fs filesystem (AWS S3 or Oracle Cloud Objects) using s3fs-fuse drivers which works similar to GlusterFS.
Marcelo.

**Comment by marcelo-ochoa** [comment]
I am working with this branch https://github.com/marcelo-ochoa/docker-volume-plugins/tree/s3fs_support testing against Oracle Cloud Object storage which is S3 compatible.
I'll make a new PR ASAP.
Marcelo.

**Comment by marcelo-ochoa** [comment]
Merged and fixed in PR (#39).

**Pull request closed without merging**
